[package]
name = "manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sha2 = { git = "https://github.com/RustCrypto/hashes", package = "sha2" }
aes-gcm = { git = "https://github.com/RustCrypto/AEADs", package = "aes-gcm" }